### ISSUE TITLE
How to use with zsh on Mac via npm install?

### ISSUE THREAD

**Issue by be-rock** [klaudiosinani/taskbook#145]
**Describe the bug**
Taskbook has been npm installed successfully (return code of `0`) but the command is _not_ found using zsh although _can_ be found with bash.

**To Reproduce**
```
$ npm install --global taskbook
...
$ echo $0; tb                                                                                                                                                                 (base) [2019-07-13 22:50:25]
-zsh
zsh: command not found: tb
$ exec /bin/bash                                                                                                                                                         (base) [2019-07-13 22:50:30] 127 ↵
bash-3.2$ echo $0; tb
/bin/bash

  Type `tb --help` to get started! ★

  0% of all tasks complete.
  0 done · 0 in-progress · 0 pending · 0 notes
```

**Expected behavior**
That the `tb` command is in the path and accessible to the `zsh` shell.  I tried `which tb` in bash but it returned nothing

**Screenshots**

**Technical Info (please complete the following information)**
 - OS: Mac OS Mojave
 - Node.js Version: 6.4.1
 - Taskbook Version: 0.3.0

**Additional context**

## Update
Resolved: But strangely only works when `~/.npm-global/bin` is the first thing in my `zsh` `PATH`.  Might be helpful to add to the install docs? 
Another possible workaround is to alias `tb` to the install location of `~/.npm-global/bin/tb` such as:
`alias tb='~/.npm-global/bin/tb'`

**Comment by be-rock** [comment]
Resolved: needed to add `~/.npm-global/bin` to my `zsh` path.  Might be helpful to add to the install docs?

**Comment by silversoul93** [comment]
It works for me in `zsh` using Macbook, but with node v12.
