### ISSUE TITLE
Example command in 'Create Note' does not work.

### ISSUE THREAD

**Issue by jinyongp** [klaudiosinani/taskbook#174]
![Screenshot from 2020-04-07 14:03:16](https://user-images.githubusercontent.com/21158729/78631942-979ae000-78d8-11ea-9ccf-e4912a228145.png)

but, `tb --note @coding Mergesort 'worse-case O(nlogn)'` works. Is it right?

**Comment by mirazmamun** [comment]
I tried the same command, both using `bash` and `zsh` on MacOS. No error. Here is my environment:
```
OS=Darwin Kernel Version 18.6.0
npm=6.14.7
node=v14.5.0
tb=0.3.0
```
Might be issue with your operating environment.
