### ISSUE TITLE
"tb" command does not work, "taskbook" does

### ISSUE THREAD

**Issue by kevigan1** [klaudiosinani/taskbook#202]
**Describe the bug**
"tb" command does not work. The progam works when i use "taskbook" in its place

**To Reproduce**
I am using Arch and Konsole

**Expected behavior**
I would expect to simply use "tb", it is less to type and what is written in the documentation.

**Technical Info (please complete the following information)**
 - OS: Arch Linux x86_64
 - Node.js Version: 21.6.1-1
 - Taskbook Version: 0.3.0-2

**Comment by atsaloli** [comment]
How did you install taskbook? I installed it with npm, and "tb" does work.

Could you add a shell alias?  e.g., `alias tb=taskbook` ?

**Comment by kevigan1** [comment]
Yes, I got it working. I should of followed up when I figured it out. I think the alias was the trick.
